from datetime import datetime


def build_verification_report(
    document_id: str,
    document_type: str,
    file_name: str,
    extracted_fields: dict,
    risk_result: dict,
    fraud_evidence: list[dict],
) -> dict:
    """
    Build a user-friendly verification report from the
    outputs generated by VeriGuard's analysis pipeline.
    """

    risk_score = risk_result.get(
        "risk_score",
        0,
    )

    risk_level = risk_result.get(
        "risk_level",
        "unknown",
    )

    decision = risk_result.get(
        "decision",
        "review_recommended",
    )

    confidence = risk_result.get(
        "confidence",
        0,
    )

    recommendation = risk_result.get(
        "recommendation",
        "Manual verification may be required.",
    )

    # --------------------------------------------------
    # HUMAN-READABLE STATUS
    # --------------------------------------------------

    status_labels = {
        "low": "LOW RISK",
        "medium": "MEDIUM RISK",
        "high": "HIGH RISK",
        "critical": "CRITICAL RISK",
    }

    status = status_labels.get(
        risk_level,
        "REVIEW REQUIRED",
    )

    # --------------------------------------------------
    # FIELD SUMMARY
    # --------------------------------------------------

    field_summary = []

    for field_name, value in extracted_fields.items():

        field_summary.append({
            "field": field_name,
            "value": value,
        })

    # --------------------------------------------------
    # EVIDENCE SUMMARY
    # --------------------------------------------------

    evidence_summary = []

    for evidence in fraud_evidence:

        evidence_summary.append({
            "type": evidence.get("type"),
            "field": evidence.get("field"),
            "title": evidence.get("title"),
            "severity": evidence.get("severity"),
            "description": evidence.get("description"),
        })

    # --------------------------------------------------
    # REPORT
    # --------------------------------------------------

    return {
        "report_id": f"VR-{document_id[:8].upper()}",

        "generated_at": datetime.now().isoformat(),

        "document": {
            "document_id": document_id,
            "file_name": file_name,
            "document_type": document_type,
        },

        "verification": {
            "status": status,
            "risk_level": risk_level,
            "risk_score": risk_score,
            "confidence": confidence,
            "decision": decision,
        },

        "extracted_fields": field_summary,

        "fraud_indicators": evidence_summary,

        "recommendation": recommendation,

        "disclaimer": (
            "This report is an automated risk assessment based "
            "on the available verification signals. It does not "
            "by itself prove that a document is genuine or fraudulent."
        ),
    }